from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable


@dataclass(frozen=True)
class LiquidityRuntimeAdapter:
    require_json_flag: Callable[..., Any]
    fail: Callable[..., int]
    ok: Callable[..., int]
    emit: Callable[..., int]
    assert_chain_capability: Callable[..., Any]
    chain_supported_hint: Callable[..., str]
    build_liquidity_adapter_for_request: Callable[..., Any]
    build_liquidity_increase_plan: Callable[..., Any]
    build_liquidity_claim_fees_plan: Callable[..., Any]
    build_liquidity_migrate_plan: Callable[..., Any]
    build_liquidity_claim_rewards_plan: Callable[..., Any]
    execute_liquidity_plan: Callable[..., Any]
    LiquidityAdapterError: type[BaseException]
    UnsupportedLiquidityAdapter: type[BaseException]
    UnsupportedLiquidityOperation: type[BaseException]
    LiquidityExecutionError: type[BaseException]
    ChainRegistryError: type[BaseException]
    WalletStoreError: type[BaseException]
    SubprocessTimeout: type[BaseException]
    _cast_call_stdout: Callable[..., Any]
    _parse_address_from_cast_output: Callable[..., str]
    _parse_uint_from_cast_output: Callable[..., int]
    _parse_uint_tuple_from_cast_output: Callable[..., Any]
    _require_chain_contract_address: Callable[..., str]
    _decimal_text: Callable[..., str]
    _fetch_erc20_metadata: Callable[..., Any]
    _format_units: Callable[..., str]
    _is_solana_chain: Callable[..., bool]
    _parse_positive_amount_text: Callable[..., Any]
    _parse_v3_range_text: Callable[..., Any]
    _resolve_raydium_pool_id: Callable[..., str]
    _resolve_token_address: Callable[..., str]
    _router_get_amount_out: Callable[..., int]
    _to_non_negative_decimal: Callable[..., Any]
    _to_units_uint: Callable[..., int]
    solana_local_quote_add: Callable[..., Any]
    solana_raydium_quote_add: Callable[..., Any]
    solana_raydium_quote_remove: Callable[..., Any]
    _api_error_details: Callable[..., dict[str, Any]]
    _api_request: Callable[..., Any]
    _liquidity_provider_settings: Callable[..., Any]
    _maybe_send_telegram_liquidity_approval_prompt: Callable[..., Any]
    _resolve_agent_id_or_fail: Callable[..., str]
    _run_liquidity_execute_inline: Callable[..., tuple[int, dict[str, Any]]]
    _compute_v2_remove_liquidity_units: Callable[..., dict[str, Any]]
    _read_v3_position_snapshot: Callable[..., dict[str, Any]]
    _resolve_liquidity_remove_tokens: Callable[..., tuple[str, str]]
    _token_symbol_for_display: Callable[..., str]
    _builder_output_from_hashes: Callable[..., dict[str, Any]]
    _cast_calldata: Callable[..., str]
    _chain_rpc_url: Callable[..., str]
    _execution_wallet: Callable[..., Any]
    _execution_wallet_solana_secret: Callable[..., Any]
    _router_action_executor: Callable[..., Any]
    load_wallet_store: Callable[..., dict[str, Any]]
    solana_local_increase_position: Callable[..., Any]
    solana_raydium_execute_instruction: Callable[..., Any]
    solana_local_claim_fees: Callable[..., Any]
    solana_local_migrate_position: Callable[..., Any]
    solana_local_claim_rewards: Callable[..., Any]
    _intent_details_dict: Callable[..., dict[str, Any]]
    _v3_details_dict: Callable[..., dict[str, Any]]
    cmd_liquidity_increase: Callable[..., int]
    cmd_liquidity_claim_fees: Callable[..., int]
    cmd_liquidity_claim_rewards: Callable[..., int]
    cmd_liquidity_migrate: Callable[..., int]
    cmd_liquidity_execute: Callable[..., int]
    _read_liquidity_intent: Callable[..., dict[str, Any]]
    _post_liquidity_status: Callable[..., Any]
    _execute_liquidity_v2_add: Callable[..., dict[str, Any]]
    _execute_liquidity_v2_remove: Callable[..., dict[str, Any]]
    _execute_liquidity_v3_add: Callable[..., dict[str, Any]]
    _execute_liquidity_v3_remove: Callable[..., dict[str, Any]]
    _wait_for_tx_receipt_success: Callable[..., dict[str, Any]]
    _build_liquidity_provider_meta: Callable[..., dict[str, Any]]
    is_hex_address: Callable[..., bool]
    _is_placeholder_liquidity_token: Callable[..., bool]
    _resolve_pair_tokens_from_contract: Callable[..., tuple[str, str]]
    _execute_liquidity_advanced_intent: Callable[..., tuple[dict[str, Any], str]]
